<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <TargetFrameworks>net9.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper.StrongName" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\YesSql.Abstractions\YesSql.Abstractions.csproj" />
    </ItemGroup>

</Project>
